### ISSUE TITLE
If MKR part of the constructor need to lock the method 

### ISSUE THREAD

**Issue by alexisgayte** [brianmcmichael/dss-vest#3]
https://github.com/brianmcmichael/dss-vest/blob/f808e8a942305dcc3409f00cf320d06283a761d8/src/DssVest.sol#L53

If the token is part of the constructor, we need to check re entrance here, cause of the external call. Mint()

**Comment by brianmcmichael** [comment]
Reentrancy check is not needed since MKR token is immutable.

**Comment by alexisgayte** [comment]
You are alright, tho there is an underlying issue if mint() delegate a call back that call back the method you can mint as much as you want. 
You either need to put the mint at the end or add re entrance check.
Probably the best solution is to add the mint at the end.

I agree that is not a problem right now tho bug happen because you change one line somewhere that you think it is safe then you have this little thing that was ignored because it wasn't a problem. ;)

I am closing this one as the other issue seems a better fix.
