### ISSUE TITLE
Cast not safe

### ISSUE THREAD

**Issue by alexisgayte** [brianmcmichael/dss-vest#6]
https://github.com/brianmcmichael/dss-vest/blob/f808e8a942305dcc3409f00cf320d06283a761d8/src/DssVest.sol#L60

Is that a safe cast?  Fin can be before bgn.

**Comment by brianmcmichael** [comment]
`uint48.max()` is 281474976710655, which is 12/07/8921556 @ 10:44am (UTC)

**Comment by alexisgayte** [comment]
Correct but this code is not correct : 
`(block.timestamp - _award.bgn) * WAD / (_award.fin - _award.bgn);`

the cast is not safe that is true.
However after reflexion the other issue is probably a better solution by cast the block.timestamp 
with uint48(block.timestamp).

I didn't see what you wanted at that time just saw the issue.

**Comment by alexisgayte** [comment]
Sorry I thought I had opened one with it ok.
I am reopened this one so with this comment

**Comment by brianmcmichael** [comment]
This is not an issue. SafeMath adds unnecessary expense here and these cannot overflow because award.bgn will always be the `block.timestamp` at the time of `init`
