### ISSUE TITLE
By convention External calls are at the end.

### ISSUE THREAD

**Issue by alexisgayte** [brianmcmichael/dss-vest#7]
https://github.com/brianmcmichael/dss-vest/blob/f808e8a942305dcc3409f00cf320d06283a761d8/src/DssVest.sol#L52

And emit is just before external call.

**Comment by brianmcmichael** [comment]
I think this is a stylistic consideration and the nice thing about using MKR is that it's not an upgradeable proxy, so we can audit it's exact behavior and so we don't need to mutex lock here. I do think that it would be better to do the Mint at the end and after the vesting accounting for clarity.

**Comment by alexisgayte** [comment]
It is not, by putting the external call at the end, you insure yourself against re-entrance as your internal logic is done.
It is like having a easy protection even if you the audit missed something.

**Comment by brianmcmichael** [comment]
There is no chance of reentrancy when calling the MKR mint function here.

**Comment by alexisgayte** [comment]
I believe it is not in that case it is more a general practice 99% of the time it won't help.

To be honest I didn't get why the security report recommended to put the emit before the external call and after the logic.
Any idea?
