### ISSUE TITLE
Don't need L70.  L71 cover for it. 

### ISSUE THREAD

**Issue by alexisgayte** [brianmcmichael/dss-vest#9]
https://github.com/brianmcmichael/dss-vest/blob/f808e8a942305dcc3409f00cf320d06283a761d8/src/DssVest.sol#L70-L71

**Comment by brianmcmichael** [comment]
Agreed.

**Comment by brianmcmichael** [comment]
Removed at 81fde5286cb717d20ad4d115d77b87ef69e265dc
